#!/bin/sh

# * License:

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -eou pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
mkdir -p "$DIR/.sandbox"

exec docker run \
     --mount type=bind,source="$DIR",target=/src \
     --mount type=bind,source="$DIR/.sandbox",target=/sandbox \
     --entrypoint=/usr/bin/emacs \
     --interactive \
     --tty \
     $(docker build . --quiet) \
     --eval "(setq user-emacs-directory (file-truename (concat \"/sandbox/\" emacs-version \"/\")))" \
     --eval "(setq user-init-file (file-truename (concat \"/sandbox/\" emacs-version \"/init.el\")))" \
     --eval "(progn (require 'package) (package-initialize))" \
     "$@"
