;; -*- mode: eask; lexical-binding: t -*-

(package ".emacs.d"
         "1.0.0"
         "Sej's Emacs Configuration")

(website-url "https://github.com/sejgit/.emacs.d")
(keywords "Emacs" "config" "osx")

;;(package-file "init.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(files "early-init.el" "init.el"
       "lisp/*.el")

(source "gnu")
(source "melpa")

(depends-on "emacs" "31.0.5")
