.PHONY: lint lint-checkdoc lint-package compile format clean help

# Emacs binary
EMACS ?= emacs

# Files to lint (main directory + lisp/, excluding custom.el which is auto-generated by Emacs)
MAIN_FILES := $(filter-out custom.el, $(wildcard *.el))
LISP_FILES := $(wildcard lisp/*.el)
ALL_FILES := $(MAIN_FILES) $(LISP_FILES)

help:
	@echo "Emacs Lisp Development Targets:"
	@echo "  make lint          - Run all linters"
	@echo "  make lint-checkdoc - Check documentation"
	@echo "  make lint-package  - Check package conventions"
	@echo "  make compile       - Byte compile all files"
	@echo "  make format        - Auto-format elisp files"
	@echo "  make clean         - Remove compiled files"

lint: lint-checkdoc compile
	@echo "✓ All linting checks passed"

lint-checkdoc:
	@echo "Running checkdoc..."
	@$(EMACS) -Q --batch \
		--eval "(setq checkdoc-force-docstrings-flag nil)" \
		--eval "(setq checkdoc-arguments-in-order-flag nil)" \
		$(foreach file,$(ALL_FILES),--eval '(checkdoc-file "$(file)")') \
		2>&1 | grep -v "^Loading" || true

lint-package:
	@echo "Running package-lint..."
	@$(EMACS) -Q --batch \
		--eval "(require 'package)" \
		--eval "(add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\"))" \
		--eval "(package-initialize)" \
		--eval "(unless (package-installed-p 'package-lint) (package-refresh-contents) (package-install 'package-lint))" \
		$(foreach file,$(filter-out init.el early-init.el,$(ALL_FILES)),--eval '(package-lint-batch-and-exit "$(file)")') \
		2>&1 | grep -v "^Loading" || true

compile:
	@echo "Byte compiling (checking for errors)..."
	@$(EMACS) -Q --batch \
		--eval "(setq byte-compile-error-on-warn nil)" \
		-f batch-byte-compile $(ALL_FILES) \
		2>&1 | grep -E "(Error|Warning):" || echo "  No errors or warnings"
	@echo "Cleaning up .elc files..."
	@find . -name "*.elc" -type f -delete

format:
	@echo "Formatting elisp files..."
	@for file in $(ALL_FILES); do \
		echo "  Formatting $$file"; \
		$(EMACS) -Q --batch "$$file" \
			--eval "(setq-default indent-tabs-mode nil)" \
			--eval "(emacs-lisp-mode)" \
			--eval "(indent-region (point-min) (point-max))" \
			--eval "(delete-trailing-whitespace)" \
			--eval "(save-buffer 0)"; \
	done
	@echo "✓ Formatting complete"

clean:
	@echo "Cleaning compiled files..."
	@find . -name "*.elc" -type f -delete
	@echo "✓ Cleaned"
